spring:
  profiles:
    active: dev
  application:
    name: template
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    multipart:
      max-file-size: -1
      max-request-size: -1

server:
  context-path: /thezp

logging:
  config: classpath:config/logback.xml
  path: /Volumes/Transcend/gitProjects/boottemplate/log
