spring:
  profiles:
    active: dev
  application:
    name: template
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    multipart:
      max-file-size: -1
      max-request-size: -1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 10
    minIdle: 10
    maxActive: 20
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: true

server:
  context-path: /thezp

logging:
  config: classpath:config/logback.xml
  path: /Volumes/Transcend/gitProjects/boottemplate/log
