spring:
  profiles:
    active: dev
  application:
    name: template

server:
  port: 9999
  context-path: /thezp

logging:
  config: classpath:config/logback.xml
  path: /Volumes/Transcend/gitProjects/boottemplate/log
