logging:
  scope: dev

server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://192.168.1.111:3306/rrs_dev?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: imssupper
    password: mnbvcxzaq

